//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsGSM.GameServer.Data {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Icon {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Icon() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsGSM.GameServer.Data.Icon", typeof(Icon).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Images/Games/7dtd.png ähnelt.
        /// </summary>
        public static string _7_Days_to_Die_Dedicated_Server {
            get {
                return ResourceManager.GetString("7 Days to Die Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Images/Games/arkse.png ähnelt.
        /// </summary>
        public static string ARK__Survival_Evolved_Dedicated_Server {
            get {
                return ResourceManager.GetString("ARK: Survival Evolved Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Images/Games/avorion.png ähnelt.
        /// </summary>
        public static string Avorion_Dedicated_Server {
            get {
                return ResourceManager.GetString("Avorion Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Images/Games/bt.png ähnelt.
        /// </summary>
        public static string Barotrauma_Dedicated_Server {
            get {
                return ResourceManager.GetString("Barotrauma Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Images/Games/bw.png ähnelt.
        /// </summary>
        public static string BlackWake_Dedicated_Server {
            get {
                return ResourceManager.GetString("BlackWake Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Images/Games/ce.png ähnelt.
        /// </summary>
        public static string Conan_Exiles_Dedicated_Server {
            get {
                return ResourceManager.GetString("Conan Exiles Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Images/Games/cs.png ähnelt.
        /// </summary>
        public static string Counter_Strike__1_6_Dedicated_Server {
            get {
                return ResourceManager.GetString("Counter-Strike: 1.6 Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Images/Games/cscz.png ähnelt.
        /// </summary>
        public static string Counter_Strike__Condition_Zero_Dedicated_Server {
            get {
                return ResourceManager.GetString("Counter-Strike: Condition Zero Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Images/Games/csgo.png ähnelt.
        /// </summary>
        public static string Counter_Strike__Global_Offensive_Dedicated_Server {
            get {
                return ResourceManager.GetString("Counter-Strike: Global Offensive Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Images/Games/css.png ähnelt.
        /// </summary>
        public static string Counter_Strike__Source_Dedicated_Server {
            get {
                return ResourceManager.GetString("Counter-Strike: Source Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Images/Games/dods.png ähnelt.
        /// </summary>
        public static string Day_of_Defeat__Source_Dedicated_Server {
            get {
                return ResourceManager.GetString("Day of Defeat: Source Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Images/Games/dod.png ähnelt.
        /// </summary>
        public static string Day_of_Defeat_Dedicated_Server {
            get {
                return ResourceManager.GetString("Day of Defeat Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Images/Games/dayz.png ähnelt.
        /// </summary>
        public static string DayZ_Dedicated_Server {
            get {
                return ResourceManager.GetString("DayZ Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Images/Games/dmc.png ähnelt.
        /// </summary>
        public static string Deathmatch_Classic_Dedicated_Server {
            get {
                return ResourceManager.GetString("Deathmatch Classic Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Images/Games/eco.png ähnelt.
        /// </summary>
        public static string Eco_Dedicated_Server {
            get {
                return ResourceManager.GetString("Eco Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Images/Games/egs.png ähnelt.
        /// </summary>
        public static string Empyrion___Galactic_Survival_Dedicated_Server {
            get {
                return ResourceManager.GetString("Empyrion - Galactic Survival Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Images/Games/gmod.png ähnelt.
        /// </summary>
        public static string Garry_s_Mod_Dedicated_Server {
            get {
                return ResourceManager.GetString("Garry\'s Mod Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Images/Games/gta5.png ähnelt.
        /// </summary>
        public static string Grand_Theft_Auto_V_Dedicated_Server__FiveM_ {
            get {
                return ResourceManager.GetString("Grand Theft Auto V Dedicated Server (FiveM)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Images/Games/hlof.png ähnelt.
        /// </summary>
        public static string Half_Life__Opposing_Force_Dedicated_Server {
            get {
                return ResourceManager.GetString("Half-Life: Opposing Force Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Images/Games/hl2dm.png ähnelt.
        /// </summary>
        public static string Half_Life_2__Deathmatch_Dedicated_Server {
            get {
                return ResourceManager.GetString("Half-Life 2: Deathmatch Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Images/Games/heat.png ähnelt.
        /// </summary>
        public static string Heat_Dedicated_Server {
            get {
                return ResourceManager.GetString("Heat Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Images/Games/inss.png ähnelt.
        /// </summary>
        public static string Insurgency__Sandstorm_Dedicated_Server {
            get {
                return ResourceManager.GetString("Insurgency: Sandstorm Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Images/Games/ins.png ähnelt.
        /// </summary>
        public static string Insurgency_Dedicated_Server {
            get {
                return ResourceManager.GetString("Insurgency Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Images/Games/l4d2.png ähnelt.
        /// </summary>
        public static string Left_4_Dead_2_Dedicated_Server {
            get {
                return ResourceManager.GetString("Left 4 Dead 2 Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Images/Games/mcbe.png ähnelt.
        /// </summary>
        public static string Minecraft__Bedrock_Edition_Server {
            get {
                return ResourceManager.GetString("Minecraft: Bedrock Edition Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Images/Games/mc.png ähnelt.
        /// </summary>
        public static string Minecraft__Java_Edition_Server {
            get {
                return ResourceManager.GetString("Minecraft: Java Edition Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Images/Games/mcpe.png ähnelt.
        /// </summary>
        public static string Minecraft__Pocket_Edition_Server__PocketMine_MP_ {
            get {
                return ResourceManager.GetString("Minecraft: Pocket Edition Server (PocketMine-MP)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Images/Games/mordhau.png ähnelt.
        /// </summary>
        public static string Mordhau_Dedicated_Server {
            get {
                return ResourceManager.GetString("Mordhau Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Images/Games/nmrih.png ähnelt.
        /// </summary>
        public static string No_More_Room_in_Hell_Dedicated_Server {
            get {
                return ResourceManager.GetString("No More Room in Hell Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Images/Games/onset.png ähnelt.
        /// </summary>
        public static string Onset_Dedicated_Server {
            get {
                return ResourceManager.GetString("Onset Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Images/Games/olow.png ähnelt.
        /// </summary>
        public static string Outlaws_of_the_Old_West_Dedicated_Server {
            get {
                return ResourceManager.GetString("Outlaws of the Old West Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Images/Games/ps.png ähnelt.
        /// </summary>
        public static string Post_Scriptum_Dedicated_Server {
            get {
                return ResourceManager.GetString("Post Scriptum Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Images/Games/rok.png ähnelt.
        /// </summary>
        public static string Reign_Of_Kings_Dedicated_Server {
            get {
                return ResourceManager.GetString("Reign Of Kings Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Images/Games/rcc.png ähnelt.
        /// </summary>
        public static string Ricochet_Dedicated_Server {
            get {
                return ResourceManager.GetString("Ricochet Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Images/Games/ror2.png ähnelt.
        /// </summary>
        public static string Risk_of_Rain_2_Dedicated_Server {
            get {
                return ResourceManager.GetString("Risk of Rain 2 Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Images/Games/rust.png ähnelt.
        /// </summary>
        public static string Rust_Dedicated_Server {
            get {
                return ResourceManager.GetString("Rust Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Images/Games/hl2dm.png ähnelt.
        /// </summary>
        public static string Source_SDK_Base_2013_Dedicated_Server {
            get {
                return ResourceManager.GetString("Source SDK Base 2013 Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Images/Games/se.png ähnelt.
        /// </summary>
        public static string Space_Engineers_Dedicated_Server {
            get {
                return ResourceManager.GetString("Space Engineers Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Images/Games/sq.png ähnelt.
        /// </summary>
        public static string Squad_Dedicated_Server {
            get {
                return ResourceManager.GetString("Squad Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Images/Games/sw.png ähnelt.
        /// </summary>
        public static string Stormworks_Dedicated_Server {
            get {
                return ResourceManager.GetString("Stormworks Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Images/Games/tf2.png ähnelt.
        /// </summary>
        public static string Team_Fortress_2_Dedicated_Server {
            get {
                return ResourceManager.GetString("Team Fortress 2 Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Images/Games/tfc.png ähnelt.
        /// </summary>
        public static string Team_Fortress_Classic_Dedicated_Server {
            get {
                return ResourceManager.GetString("Team Fortress Classic Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Images/Games/tf.png ähnelt.
        /// </summary>
        public static string The_Forest_Dedicated_Server {
            get {
                return ResourceManager.GetString("The Forest Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Images/Games/unt.png ähnelt.
        /// </summary>
        public static string Unturned_Dedicated_Server {
            get {
                return ResourceManager.GetString("Unturned Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Images/Games/vts.png ähnelt.
        /// </summary>
        public static string Vintage_Story_Dedicated_Server {
            get {
                return ResourceManager.GetString("Vintage Story Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Images/Games/zps.png ähnelt.
        /// </summary>
        public static string Zombie_Panic_Source_Dedicated_Server {
            get {
                return ResourceManager.GetString("Zombie Panic Source Dedicated Server", resourceCulture);
            }
        }
    }
}
